import java.util.ArrayList;
/*
 * DO NOT EDIT THIS FILE
 */
public interface ICar {   
    /*
     * calculate and return last name of 
     * color that have maximum number of cars in list a
     */  
    public String f1(ArrayList<Car> a);        
    /*
     * calculate and return the number of car in the list a that have 
     * greater less than or equals to 50000
     */   
    public int f2(ArrayList<Car> a);
}
