import java.util.ArrayList;
/*
 * DO NOT EDIT THIS FILE
 */
public interface ICake {   
    /**
     * Get the name of the first Cake which has highest sales price
     * @param a - list of Cake objects
     * @return - name of the first cake which has highest sales price
     */
    public String getHighestPrice(ArrayList<Cake> a);        
    /**
     * Get return the number of Cakes that have imported tax  
     * less than the imported tax of the first Cake in the list
     * @param a - list of Cake objects
     * @return - number of Cakes that have imported tax  
     * less than the imported tax of the first Cake in the list
     */
    public int count(ArrayList<Cake> a);
}
